package com.eebochina.train.analytics.common

enum class UpgradeEnum
    (val upgradeNum: String) {
    LIVE_BROADCAST_ONLINE("1"),
    PERSONNEL_STATISTICS("2"),
    CUSTOM_SCHEMA("3"),
    SALARY_STATISTICAL_ANALYSIS("4"),
    ENTERPRISE_WECHAT_PUNCH_IN("5"),
    ATTENDANCE_MACHINE_MANAGEMENT("6"),
    RANK_SYSTEM("7"),
    SOCIAL_SECURITY_ACCUMULATION_FUND("8"),
    SECURITY_SETTING("9"),
    RECRUITMENT_ANALYSIS("10"),
    APP_STATISTICAL_ANALYSIS("11"),
    UPGRADE_ENTERPRISE_VERSION_IN_APP("12"),
}
